server:
  port: 7771
logging:
  level:
    root: DEBUG
spring:
  application:
    name: AuthorizationService
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webprotege
      auto-index-creation: true

webprotege.rabbitmq:
  timeout: 60000
  requestqueue: webprotege-authorization-queue
  responsequeue: webprotege-authorization-response-queue

keycloak-issuer-url: http://webprotege-local.edu/auth/realms/webprotege/protocol/openid-connect/certs
