server:
  port: 8083

webprotege:
  database:
    name: webprotege

spring.data.mongodb.auto-index-creation: true

spring:
  application:
    name: AuthorizationService
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}


#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#spring:
#  kafka:
#    producer:
#      value-serializer=org:
#        springframework:
#          kafka:
#            support:
#              serializer:
#                StringOrBytesSerializer: