server:
  port: 7771

spring:
  application:
    name: AuthorizationService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webprotege
      auto-index-creation: true

logging:
  level:
    root: DEBUG