server:
  port: 7771

spring:
  application:
    name: AuthorizationService
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webprotege
      auto-index-creation: true

webprotege.rabbitmq:
  requestqueue: webprotege-authorization-queue
  responsequeue: webprotege-authorization-response-queue
  timeout: 60000

keycloak-issuer-url: http://webprotege-local.edu/auth/realms/webprotege/protocol/openid-connect/certs
