server:
  port: 7771

spring:
  application:
    name: AuthorizationService
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webprotege
      auto-index-creation: true